development:
  adapter: postgresql
  encoding: unicode
  database: dabcab_development
  pool: 5
  username: boom
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dabcab_test
  pool: 5
  username: boom
  password:
